//! The UniFFI facade the macOS shell calls: a thin surface over
//! `openimzo-keys`, `openimzo-rpc` and `openimzo-server`, expressed in only the types
//! and calls the spec's section 3.6 gives the Swift side. `Engine`'s
//! lifecycle, its records, the `Platform`/`UiDelegate` callback interfaces,
//! the event stream, the key operations, settings persistence and the
//! sites list are all landed now — every call section 3.6 names.

// `include_scaffolding!` below splices UniFFI's generated code directly into
// this crate root, doc comment and all; the generated comment trips
// `clippy::empty_line_after_doc_comments` on the constant right after it.
// Nothing here to fix — the source is regenerated by `build.rs` on every
// build — so the lint is silenced for the whole crate rather than chasing a
// warning in code this crate does not own.
#![allow(clippy::empty_line_after_doc_comments)]

mod delegate;
mod engine;
mod events;
mod identity;
mod settings;
mod types;

pub use delegate::{
    NewPfxAnswer, NewPfxRequest, PasswordAnswer, PasswordRequest, PermissionAnswer, PermissionRequest, Platform,
    UiDelegate,
};
pub use engine::Engine;
pub use events::{Event, EventStream};
pub use types::{ActivityEntry, EngineConfig, EngineError, EngineStatus, KeyEntry, Settings, Site};

uniffi::include_scaffolding!("openimzo");
