[package]
name = "openimzo-pki"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PKCS#12, YTKS-2, X.509, CMS and PKCS#10 for OpenImzo"

[dependencies]
openimzo-crypto = { path = "../openimzo-crypto" }
der.workspace = true
spki.workspace = true
pkcs8.workspace = true
x509-cert.workspace = true
cms.workspace = true
pkcs12.workspace = true
pkcs5.workspace = true
const-oid.workspace = true
num-bigint.workspace = true
subtle.workspace = true
rand_core.workspace = true
sha1.workspace = true
sha2.workspace = true
hmac.workspace = true
des.workspace = true
rc2.workspace = true
cbc.workspace = true
cipher.workspace = true
hex.workspace = true
base64.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
zeroize.workspace = true
